// Promotion categories
export const PROMOTION_CATEGORIES = [
  { id: "all", label: "Tất cả", icon: "🎯" },
  { id: "food", label: "Đồ ăn", icon: "🍔" },
  { id: "vehicle", label: "Xe cộ", icon: "🚗" },
  { id: "delivery", label: "Giao hàng", icon: "📦" },
  { id: "gift", label: "Quà tặng", icon: "🎁" },
  { id: "combo", label: "Combo", icon: "💰" },
];

// Mock promotion data
export const MOCK_PROMOTIONS = [
  {
    id: 1,
    title: "Deal Hè Của Đá",
    subtitle: "Món Ngon Giảm Giá Cực Sốc",
    bgColor: "bg-green-500",
    image: "🧊",
    category: "food",
    discount: "30%",
    validUntil: "31/08/2025",
  },
  {
    id: 2,
    title: "DEAL HÈ CỰC ĐÃ",
    subtitle: "ĐẢ - MÓN NGON GIẢM GIÁ",
    bgColor: "bg-orange-500",
    image: "☀️",
    category: "food",
    discount: "25%",
    validUntil: "15/08/2025",
  },
  {
    id: 3,
    title: "ĐẶT MÓN VIP",
    subtitle: "GIAO - KHAO MIỄN PHÍ",
    bgColor: "bg-red-500",
    image: "👑",
    category: "food",
    discount: "Free Ship",
    validUntil: "30/07/2025",
  },
  {
    id: 4,
    title: "THUÊ XE GIÁ SỐC",
    subtitle: "Giảm 50% Chuyến Đầu",
    bgColor: "bg-blue-500",
    image: "🚗",
    category: "vehicle",
    discount: "50%",
    validUntil: "20/08/2025",
  },
  {
    id: 5,
    title: "XE MÁY TIẾT KIỆM",
    subtitle: "Combo 3 Chuyến Chỉ 99K",
    bgColor: "bg-cyan-500",
    image: "🏍️",
    category: "vehicle",
    discount: "99K",
    validUntil: "25/08/2025",
  },
  {
    id: 6,
    title: "GIAO HÀNG EXPRESS",
    subtitle: "Nhanh Trong 30 Phút",
    bgColor: "bg-purple-500",
    image: "⚡",
    category: "delivery",
    discount: "20%",
    validUntil: "10/08/2025",
  },
  {
    id: 7,
    title: "QUÀ TẶNG ĐẶC BIỆT",
    subtitle: "Mua 1 Tặng 1",
    bgColor: "bg-pink-500",
    image: "🎁",
    category: "gift",
    discount: "Buy 1 Get 1",
    validUntil: "05/08/2025",
  },
  {
    id: 8,
    title: "COMBO TIẾT KIỆM",
    subtitle: "Ăn + Xe Chỉ 199K",
    bgColor: "bg-indigo-500",
    image: "💰",
    category: "combo",
    discount: "199K",
    validUntil: "31/07/2025",
  },
];
